### ISSUE TITLE
Downloading wikipedia maxi fails: suggest adding a work around to the documentation

### ISSUE THREAD

**Issue by cacology** [kiwix/kiwix-apple#1029] opened 2024-11-15 16:31 UTC
On Kiwix 3.5.2 build 173 running on iOS 18.0.1 on an iPhone 14 Pro, downloading via the in-app categories fails for `wikipedia_en_all_maxi_2024-01.zim`.  The whole file would begin downloading, get to 100% over a few hours, then it would simply disappear without an error.

Other zim files downloaded without a problem and the iPhone has sufficient storage.

I tried it several times on several wifi networks on several different days.  This seems to be an ongoing and difficult to diagnose problem with checking the integrity of downloads related to #452 and others.

I overcame the issue by downloading the file directly from download.kiwix.org and moving it to my iPhone using the Sync->File dialog in Finder and dropping it right into the Kiwix app.  See screenshot:

![Image](https://github.com/user-attachments/assets/8f768b66-532c-4843-bdbd-6f3d6d58960f)

I'd suggest adding the workaround to the documentation: download the file from the website and move it over with Finder.

I'm happy to provide more diagnostic information, if that would help someone, but I'm not sure it would be useful.

Respectfully submitted,

**Comment by kelson42** [comment] 2024-11-15 17:59
@BPerlakiH Can you confirm this is a duplicate of #992 please?

**Comment by BPerlakiH** [comment] 2024-11-18 10:41
@cacology @kelson42 Yes, it seems to be a duplicate of #992.
It is fixed in 3.60, which is to be released soonish, the intermediate work around for this is either as you did via Finder / AirDrop adding the file, or you can also "import" the file into the app, once downloaded (externally), by opening it from the app, or opening it from iPhone "Files" application.

**Closed** 2024-11-18 11:53 UTC
Labels: bug, duplicate
