### ISSUE TITLE
Document how to get Kiwix debug log in Chrome

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#782] opened 2024-05-31 11:18 UTC

**Comment by BPerlakiH** [comment] 2024-05-31 13:01
I think what you had in mind is in Safari. There's an Apple documentation on this one:
https://developer.apple.com/documentation/safari-developer-tools/inspecting-ios

**Comment by BPerlakiH** [comment] 2024-06-20 20:30
Closing this as a duplicate of: https://github.com/kiwix/kiwix-apple/issues/788

**Closed by BPerlakiH** 2024-06-20 20:30 UTC
