### ISSUE TITLE
Unable to search with Japanese Dakuon or Handakuon

### ISSUE THREAD

**Issue by RuochenFu21** [kiwix/kiwix-apple#734] opened 2024-04-22 07:27 UTC
I'm on Wiktionary. And when I search anything with Dakuon or Handakakuon, it won't show up anything.
For people that don't know Japanese. Basically, when you search anything contains がぎぐげご、ざじずぜぞ、だぢづでど、ばびぶべぼ、ぱぴぷぺぽ、ゔヴ、ガギグゲホ、ザジズぜぞ、ダヂヅデド、バビブベボ、パピプペポ、etc... it won't show up anything, even though those articles clearly exist, every one of those characters itself have a article with name of that character.

**Comment by kelson42** [comment] 2024-04-22 08:02
@RuochenFu21 Thank you for rhis bug report. This bug is know and actually fixed in our code base (libzim). Unfortunately, MWofflinaire, rhe Wiktionary scraper still rely on an older version of the libzim. This is on the roadmap to use latest version, but this might take a few additional months.

**Comment by RuochenFu21** [comment] 2024-04-22 10:16
Oh that's interesting, thanks for replying

**Comment by kelson42** [comment] 2024-05-14 04:22
[MWoffliner isue](https://github.com/openzim/mwoffliner/issues/1576)

**Comment by kelson42** [comment] 2024-05-14 04:59
@RuochenFu21 Actually I would be interest to know if the search works correctly with https://library.kiwix.org/#lang=&category=iFixit iFixit in Japanese. This ZIM file has been made with a recent version of the libzim.

**Comment by RuochenFu21** [comment] 2024-05-14 05:09
> @RuochenFu21 Actually I would be interest to know if the search works correctly with https://library.kiwix.org/#lang=&category=iFixit iFixit in Japanese. This ZIM file has been made with a recent version of the libzim.

I only see some books, how should I apply it?

**Comment by RuochenFu21** [comment] 2024-05-14 05:35
> @RuochenFu21 Actually I would be interest to know if the search works correctly with https://library.kiwix.org/#lang=&category=iFixit iFixit in Japanese. This ZIM file has been made with a recent version of the libzim.

I'll try when I have time

**Comment by kelson42** [comment] 2024-07-12 10:16
Duplicate of #847

**Closed by kelson42** 2024-07-12 10:16 UTC
Labels: bug, upstream, duplicate

**Comment by iphoneio** [comment] 2024-09-01 03:10
Even in Kiwix 3.5.1, the Mac version cannot search for Japanese characters with diacritical marks or katakana. Without the ability to search, this app becomes almost useless. If possible, please fix this in the next update.
![Uploading Kiwix Wiki.jpg…]()

**Comment by iphoneio** [comment] 2024-09-01 03:11
Even in Kiwix 3.5.1, the Mac version cannot search for Japanese characters with diacritical marks or katakana. Without the ability to search, this app becomes almost useless. If possible, please fix this in the next update.

![KiwixWiki](https://github.com/user-attachments/assets/baf9beb5-bb09-4a21-b1e5-64bfa0f60df1)
