### ISSUE TITLE
Clicking on a fullscreen video results in forever black screen

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-apple#889] opened 2024-07-29 07:23 UTC
Scraper: youtube (but probably other are impacted the same)
App version: 3.4.1 (170) via TestFlight
OS: Mac OS Sonoma 14.5

ZIM tested:
- https://download.kiwix.org/zim/videos/avanti-3dimensional-geometry_2024-03.zim (old one, where sound does not work)
- https://download.kiwix.org/zim/videos/avanti-3dimensional-geometry_2024-06.zim (new one, with VP9 videos, sound working, ...)

Steps to reproduce the bug:
- start a video
- go into fullscreen
- click with the mouse in the fullscreen (not on the control bars, but anywhere in the video) => the video stops
- click again in the full screen => the sound resume but the video stays black in fullscreen

Note that from the moment the bug appears, the fullscreen is always black but if we exit fullscreen video plays well again

Note also that close the Kiwix window (not the app, only the window) is sufficient to restore fullscreen working properly.

**Comment by BPerlakiH** [comment] 2024-07-30 09:36
Thank you @benoit74 for reporting this.

I am able to fully reproduce it with the provided videos.
I have retested this case with the test videos provided by @rgaudin:
<img width="275" alt="Screenshot 2024-07-30 at 11 30 29" src="https://github.com/user-attachments/assets/fb9a9053-1e7c-4bec-a4a8-6efb8434a21b">

This is, what I have found so far:

The reported ZIM is using:
- webm + Video.js 8.6.1 + videojs-ogvjs @version 2.0.0

This issue won't occur in the test videos, which are using:
- webm + no video js (pure html video tag)
- mp4 + video js "8.12.0"; + ogv V = "1.9.0-20240423190513-22f6924"


Do you think we can fix it on the content side?

**Comment by kelson42** [comment] 2024-07-30 10:35
> Do you think we can fix it on the content side?

No we can't. I don't understand how we have missed this?! It has clearly been stated that this was working at 3.4.0 release, so what happened?

**Comment by BPerlakiH** [comment] 2024-07-30 14:09
@kelson42 I think we tested some of the combinations of video js and no js versions, and I suppose based on that we assumed it will always work. The reported ZIM file is using video js release from "Oct 12, 2023". I don't remember any discussion around specific versions of videojs (or ogv.js) that we meant to support.

The good news is that it works without those JS files, and since the content cannot be changed on the input size, that lead me to the following:

The most "brutal" and simplest / "hacky" fix I have found, is to block the loading of any ".js" file containing "video" or "ogv" in the filename. This blocks the javascript part, and fixes this issue (at least on macOS, where I've tested).

What do think about it?

**Comment by kelson42** [comment] 2024-07-30 16:10
> @kelson42 I think we tested some of the combinations of video js ogv js versions and no js (html tag only). I suppose based on that we might have assumed it will always work. The reported ZIM file is using video js release from "Oct 12, 2023". I don't remember any discussion around specific versions of videojs (or ogv.js) that we meant to support.

We have tested with the very same test file from @rgaudin with very similar setup....

> The good news is that it works without those JS files, and since the content input cannot be changed... that lead me to the following:

This is not a good news, almost all our files use video.js

> The most "brutal" and simplest / "hacky" fix I have found, is to block the loading of any ".js" file containing "video" or "ogv" in the filename. This blocks the javascript part, and fixes this issue (at least on macOS, where I've tested).
> 
> What do think about it?

Not acceptable. Please never develop a fix before we fully can explain a bug.

@BPerlakiH So you confirm that all our TED/Youtube ZIM files are impacted by this bug on most recent version of macOS and Kiwix?

**Comment by BPerlakiH** [comment] 2024-07-30 22:26
I did look into this one:

Version 3.3.0 was released to macOS, without supporting full screen mode (only inline player).

Version 3.4.0 and everything above is affected by this bug on macOS (14.5), including videos such as: 
- TED Addiction videos
- TED Pain
- Canadian prepper

**Comment by kelson42** [comment] 2024-07-31 05:02
OK, so now we need to understand the rootcause behind this bug.

**Comment by BPerlakiH** [comment] 2024-07-31 12:36
It turned out that auto layout is not working properly with the "going into full screen functionality" for some reason... It is occurring immediately when we have video.js turned on, and after a couple of attempts of toggling full-screen not full-screen, if we do not have video.js.

I did a fix for this here:
https://github.com/kiwix/kiwix-apple/pull/893

**Closed** 2024-08-01 15:43 UTC
Labels: bug
