### ISSUE TITLE
Files not completing downloading

### ISSUE THREAD

**Issue by fahasneeds** [kiwix/kiwix-apple#1001] opened 2024-10-06 12:04 UTC
I'm using an iPad Air (5th Generation), on IOS 18.0.1 and my Kiwix version 3.5.2

I have tried to download Wikipedia (max 109.89 GB) and (no pic 57.18 GB) multiple times, however each time the file has downloaded, it does not appear in the available files offline, and my iPad memory does not reduce by the corresponding amount of GB. I have checked that I have more than enough space on my iPad to download the files.

May I check if that has been reported as an issue and if it could be resolved?

Thank you so much for your help.

**Comment by kelson42** [comment] 2024-10-06 12:40
@fahasneeds Thank you very much for opening an issue. I supsect this is a duplicate of #992. @BPerlakiH Could you please confirm?

**Comment by BPerlakiH** [comment] 2024-10-06 15:28
Yes it seems to be a duplicate of #992.

**Comment by BPerlakiH** [comment] 2024-10-06 17:34
I have retested once more with a 40GB file on the iPad (only having 41GB available), and after the [PR](https://github.com/kiwix/kiwix-apple/pull/998) it works well.

**Closed by BPerlakiH** 2024-10-06 17:34 UTC
Labels: bug, duplicate
