### ISSUE TITLE
Unable to search with 人 as the third or later character

### ISSUE THREAD

**Issue by RuochenFu21** [kiwix/kiwix-apple#762] opened 2024-05-10 07:32 UTC
I'm using Wiktionary
I searched for "中国人", nothing comes up, but something do when I search 中国

When I tried "一路人" to see if it have problem with "国人", still nothing come up

When I tried "千古罪人" to check for the fourth, still nothing comes up.

And when I tried "大人" and "人" which is on the first 2 char, it magically worked. 

Also this is still a problem when more characters go after that, "深入人心" can't be searched

Not sure if this happens with any other characters.

**Comment by kelson42** [comment] 2024-05-12 16:03
@RuochenFu21 Thank you for your bug report. This is a known problem which finds its root cause in he scraper MWoffliner which should use the latest version of the libzim.

**Comment by kelson42** [comment] 2024-05-14 04:19
Actually a duplicate of https://github.com/openzim/mwoffliner/issues/1576.

@RuochenFu21 Which language is this exactly?

**Comment by kelson42** [comment] 2024-05-14 04:21
Duplicate of #734

**Closed by kelson42** 2024-05-14 04:21 UTC
Labels: bug, question

**Comment by RuochenFu21** [comment] 2024-08-06 04:50
> Actually a duplicate of [openzim/mwoffliner#1576](https://github.com/openzim/mwoffliner/issues/1576).
> 
> @RuochenFu21 Which language is this exactly?

Chinese / Japanese
